component_depth: 1
languages:
- java
exclude:
- ./apps/.*
- ./bin/.*
- ./bin/com/.*
- ./bin/com/opensymphony/.*
- ./bin/com/opensymphony/xwork2/.*
- ./bin/com/opensymphony/xwork2/config/.*
- ./bin/com/opensymphony/xwork2/config/entities/.*
- ./bin/com/opensymphony/xwork2/config/impl/.*
- ./bin/com/opensymphony/xwork2/config/providers/.*
- ./bin/com/opensymphony/xwork2/conversion/.*
- ./bin/com/opensymphony/xwork2/conversion/annotations/.*
- ./bin/com/opensymphony/xwork2/conversion/impl/.*
- ./bin/com/opensymphony/xwork2/conversion/metadata/.*
- ./bin/com/opensymphony/xwork2/inject/.*
- ./bin/com/opensymphony/xwork2/inject/util/.*
- ./bin/com/opensymphony/xwork2/interceptor/.*
- ./bin/com/opensymphony/xwork2/interceptor/annotations/.*
- ./bin/com/opensymphony/xwork2/mock/.*
- ./bin/com/opensymphony/xwork2/ognl/.*
- ./bin/com/opensymphony/xwork2/ognl/accessor/.*
- ./bin/com/opensymphony/xwork2/spring/.*
- ./bin/com/opensymphony/xwork2/spring/interceptor/.*
- ./bin/com/opensymphony/xwork2/test/.*
- ./bin/com/opensymphony/xwork2/test/annotations/.*
- ./bin/com/opensymphony/xwork2/test/subtest/.*
- ./bin/com/opensymphony/xwork2/util/.*
- ./bin/com/opensymphony/xwork2/util/classloader/.*
- ./bin/com/opensymphony/xwork2/util/finder/.*
- ./bin/com/opensymphony/xwork2/util/location/.*
- ./bin/com/opensymphony/xwork2/util/logging/.*
- ./bin/com/opensymphony/xwork2/util/logging/commons/.*
- ./bin/com/opensymphony/xwork2/util/logging/jdk/.*
- ./bin/com/opensymphony/xwork2/util/profiling/.*
- ./bin/com/opensymphony/xwork2/util/reflection/.*
- ./bin/com/opensymphony/xwork2/validator/.*
- ./bin/com/opensymphony/xwork2/validator/annotations/.*
- ./bin/com/opensymphony/xwork2/validator/metadata/.*
- ./bin/com/opensymphony/xwork2/validator/validators/.*
- ./bin/example/.*
- ./bin/it/.*
- ./bin/it/org/.*
- ./bin/it/org/apache/.*
- ./bin/it/org/apache/struts2/.*
- ./bin/it/org/apache/struts2/rest/.*
- ./bin/it/org/apache/struts2/rest/example/.*
- ./bin/it/org/apache/struts2/showcase/.*
- ./bin/it/org/apache/struts2/showcase/staticcontent/.*
- ./bin/mailreader2/.*
- ./bin/org/.*
- ./bin/org/apache/.*
- ./bin/org/apache/struts2/.*
- ./bin/org/apache/struts2/codebehind/.*
- ./bin/org/apache/struts2/compiler/.*
- ./bin/org/apache/struts2/components/.*
- ./bin/org/apache/struts2/components/template/.*
- ./bin/org/apache/struts2/config/.*
- ./bin/org/apache/struts2/config/cltest/.*
- ./bin/org/apache/struts2/config/parenttest/.*
- ./bin/org/apache/struts2/config_browser/.*
- ./bin/org/apache/struts2/convention/.*
- ./bin/org/apache/struts2/convention/actions/.*
- ./bin/org/apache/struts2/convention/actions/action/.*
- ./bin/org/apache/struts2/convention/actions/chain/.*
- ./bin/org/apache/struts2/convention/actions/defaultinterceptor/.*
- ./bin/org/apache/struts2/convention/actions/exception/.*
- ./bin/org/apache/struts2/convention/actions/idx/.*
- ./bin/org/apache/struts2/convention/actions/idx/idx2/.*
- ./bin/org/apache/struts2/convention/actions/interceptor/.*
- ./bin/org/apache/struts2/convention/actions/namespace/.*
- ./bin/org/apache/struts2/convention/actions/namespace2/.*
- ./bin/org/apache/struts2/convention/actions/namespace3/.*
- ./bin/org/apache/struts2/convention/actions/namespace4/.*
- ./bin/org/apache/struts2/convention/actions/params/.*
- ./bin/org/apache/struts2/convention/actions/parentpackage/.*
- ./bin/org/apache/struts2/convention/actions/parentpackage/sub/.*
- ./bin/org/apache/struts2/convention/actions/result/.*
- ./bin/org/apache/struts2/convention/actions/resultpath/.*
- ./bin/org/apache/struts2/convention/actions/skip/.*
- ./bin/org/apache/struts2/convention/annotation/.*
- ./bin/org/apache/struts2/convention/dontfind/.*
- ./bin/org/apache/struts2/dispatcher/.*
- ./bin/org/apache/struts2/dispatcher/mapper/.*
- ./bin/org/apache/struts2/dispatcher/multipart/.*
- ./bin/org/apache/struts2/dispatcher/ng/.*
- ./bin/org/apache/struts2/dispatcher/ng/filter/.*
- ./bin/org/apache/struts2/dispatcher/ng/listener/.*
- ./bin/org/apache/struts2/dispatcher/ng/servlet/.*
- ./bin/org/apache/struts2/dojo/.*
- ./bin/org/apache/struts2/dojo/components/.*
- ./bin/org/apache/struts2/dojo/views/.*
- ./bin/org/apache/struts2/dojo/views/freemarker/.*
- ./bin/org/apache/struts2/dojo/views/freemarker/tags/.*
- ./bin/org/apache/struts2/dojo/views/jsp/.*
- ./bin/org/apache/struts2/dojo/views/jsp/ui/.*
- ./bin/org/apache/struts2/dojo/views/velocity/.*
- ./bin/org/apache/struts2/dojo/views/velocity/components/.*
- ./bin/org/apache/struts2/el/.*
- ./bin/org/apache/struts2/el/lang/.*
- ./bin/org/apache/struts2/el/parser/.*
- ./bin/org/apache/struts2/el/util/.*
- ./bin/org/apache/struts2/impl/.*
- ./bin/org/apache/struts2/interceptor/.*
- ./bin/org/apache/struts2/interceptor/debugging/.*
- ./bin/org/apache/struts2/interceptor/validation/.*
- ./bin/org/apache/struts2/jasper/.*
- ./bin/org/apache/struts2/jasper/compiler/.*
- ./bin/org/apache/struts2/jasper/compiler/tagplugin/.*
- ./bin/org/apache/struts2/jasper/el/.*
- ./bin/org/apache/struts2/jasper/runtime/.*
- ./bin/org/apache/struts2/jasper/security/.*
- ./bin/org/apache/struts2/jasper/servlet/.*
- ./bin/org/apache/struts2/jasper/tagplugins/.*
- ./bin/org/apache/struts2/jasper/tagplugins/jstl/.*
- ./bin/org/apache/struts2/jasper/tagplugins/jstl/core/.*
- ./bin/org/apache/struts2/jasper/util/.*
- ./bin/org/apache/struts2/jasper/xmlparser/.*
- ./bin/org/apache/struts2/jsf/.*
- ./bin/org/apache/struts2/json/.*
- ./bin/org/apache/struts2/json/annotations/.*
- ./bin/org/apache/struts2/json/rpc/.*
- ./bin/org/apache/struts2/json/smd/.*
- ./bin/org/apache/struts2/osgi/.*
- ./bin/org/apache/struts2/osgi/interceptor/.*
- ./bin/org/apache/struts2/osgi/loaders/.*
- ./bin/org/apache/struts2/oval/.*
- ./bin/org/apache/struts2/oval/annotation/.*
- ./bin/org/apache/struts2/oval/interceptor/.*
- ./bin/org/apache/struts2/oval/interceptor/domain/.*
- ./bin/org/apache/struts2/plexus/.*
- ./bin/org/apache/struts2/portlet/.*
- ./bin/org/apache/struts2/portlet/context/.*
- ./bin/org/apache/struts2/portlet/dispatcher/.*
- ./bin/org/apache/struts2/portlet/example/.*
- ./bin/org/apache/struts2/portlet/example/fileupload/.*
- ./bin/org/apache/struts2/portlet/example/model/.*
- ./bin/org/apache/struts2/portlet/example/spring/.*
- ./bin/org/apache/struts2/portlet/interceptor/.*
- ./bin/org/apache/struts2/portlet/result/.*
- ./bin/org/apache/struts2/portlet/servlet/.*
- ./bin/org/apache/struts2/portlet/test/.*
- ./bin/org/apache/struts2/portlet/util/.*
- ./bin/org/apache/struts2/rest/.*
- ./bin/org/apache/struts2/rest/example/.*
- ./bin/org/apache/struts2/rest/handler/.*
- ./bin/org/apache/struts2/s1/.*
- ./bin/org/apache/struts2/servlet/.*
- ./bin/org/apache/struts2/servlet/interceptor/.*
- ./bin/org/apache/struts2/showcase/.*
- ./bin/org/apache/struts2/showcase/action/.*
- ./bin/org/apache/struts2/showcase/actionchaining/.*
- ./bin/org/apache/struts2/showcase/ajax/.*
- ./bin/org/apache/struts2/showcase/ajax/tree/.*
- ./bin/org/apache/struts2/showcase/application/.*
- ./bin/org/apache/struts2/showcase/chat/.*
- ./bin/org/apache/struts2/showcase/conversion/.*
- ./bin/org/apache/struts2/showcase/dao/.*
- ./bin/org/apache/struts2/showcase/exception/.*
- ./bin/org/apache/struts2/showcase/filedownload/.*
- ./bin/org/apache/struts2/showcase/fileupload/.*
- ./bin/org/apache/struts2/showcase/freemarker/.*
- ./bin/org/apache/struts2/showcase/hangman/.*
- ./bin/org/apache/struts2/showcase/integration/.*
- ./bin/org/apache/struts2/showcase/jsf/.*
- ./bin/org/apache/struts2/showcase/model/.*
- ./bin/org/apache/struts2/showcase/modelDriven/.*
- ./bin/org/apache/struts2/showcase/person/.*
- ./bin/org/apache/struts2/showcase/tag/.*
- ./bin/org/apache/struts2/showcase/tag/nonui/.*
- ./bin/org/apache/struts2/showcase/tag/nonui/actionPrefix/.*
- ./bin/org/apache/struts2/showcase/tag/nonui/actiontag/.*
- ./bin/org/apache/struts2/showcase/tag/nonui/iteratortag/.*
- ./bin/org/apache/struts2/showcase/token/.*
- ./bin/org/apache/struts2/showcase/validation/.*
- ./bin/org/apache/struts2/showcase/wait/.*
- ./bin/org/apache/struts2/showcase/xslt/.*
- ./bin/org/apache/struts2/sitegraph/.*
- ./bin/org/apache/struts2/sitegraph/entities/.*
- ./bin/org/apache/struts2/sitegraph/model/.*
- ./bin/org/apache/struts2/sitegraph/renderers/.*
- ./bin/org/apache/struts2/sitemesh/.*
- ./bin/org/apache/struts2/spring/.*
- ./bin/org/apache/struts2/tiles/.*
- ./bin/org/apache/struts2/util/.*
- ./bin/org/apache/struts2/validators/.*
- ./bin/org/apache/struts2/views/.*
- ./bin/org/apache/struts2/views/annotations/.*
- ./bin/org/apache/struts2/views/freemarker/.*
- ./bin/org/apache/struts2/views/freemarker/tags/.*
- ./bin/org/apache/struts2/views/gxp/.*
- ./bin/org/apache/struts2/views/jasperreports/.*
- ./bin/org/apache/struts2/views/java/.*
- ./bin/org/apache/struts2/views/java/simple/.*
- ./bin/org/apache/struts2/views/jsp/.*
- ./bin/org/apache/struts2/views/jsp/iterator/.*
- ./bin/org/apache/struts2/views/jsp/ui/.*
- ./bin/org/apache/struts2/views/tiles/.*
- ./bin/org/apache/struts2/views/util/.*
- ./bin/org/apache/struts2/views/velocity/.*
- ./bin/org/apache/struts2/views/velocity/components/.*
- ./bin/org/apache/struts2/views/xslt/.*
- ./docs/.*
- ./docs/S2PLUGINS/.*
- ./docs/S2PLUGINS/2009/.*
- ./docs/S2PLUGINS/2009/12/.*
- ./docs/S2PLUGINS/2009/12/15/.*
- ./docs/S2PLUGINS/2010/.*
- ./docs/S2PLUGINS/2010/01/.*
- ./docs/S2PLUGINS/2010/01/20/.*
- ./docs/S2PLUGINS/2010/01/25/.*
- ./docs/S2PLUGINS/2010/01/30/.*
- ./docs/S2PLUGINS/2010/02/.*
- ./docs/S2PLUGINS/2010/02/04/.*
- ./docs/S2PLUGINS/2010/03/.*
- ./docs/S2PLUGINS/2010/03/08/.*
- ./docs/S2PLUGINS/2010/03/11/.*
- ./docs/S2PLUGINS/2010/03/22/.*
- ./docs/S2PLUGINS/2010/03/23/.*
- ./docs/S2PLUGINS/2010/03/30/.*
- ./docs/S2PLUGINS/2010/04/.*
- ./docs/S2PLUGINS/2010/04/19/.*
- ./docs/S2PLUGINS/2010/05/.*
- ./docs/S2PLUGINS/2010/05/10/.*
- ./docs/S2PLUGINS/2010/05/30/.*
- ./docs/S2PLUGINS/2010/06/.*
- ./docs/S2PLUGINS/2010/06/08/.*
- ./docs/S2PLUGINS/2010/06/09/.*
- ./docs/S2PLUGINS/connext-graph-plugin.data/.*
- ./docs/S2PLUGINS/yui-plugin.data/.*
- ./docs/WW/.*
- ./docs/WW/ajax-validation.data/.*
- ./docs/WW/apache-struts-pseudo-nightly-builds-on-apache-hudson.data/.*
- ./docs/WW/asynchronous-processing-with-webwork-xwork.data/.*
- ./docs/WW/big-picture.data/.*
- ./docs/WW/coding-struts-2-actions.data/.*
- ./docs/WW/create-struts-2-web-application-using-maven-to-manage-artifacts-and-to-build-the-application.data/.*
- ./docs/WW/create-struts-2-web-application-with-artifacts-in-web-inf-lib-and-use-ant-to-build-the-application.data/.*
- ./docs/WW/debugging-struts.data/.*
- ./docs/WW/form-validation-using-xml.data/.*
- ./docs/WW/form-validation.data/.*
- ./docs/WW/hello-world-using-struts-2.data/.*
- ./docs/WW/interceptors.data/.*
- ./docs/WW/nutshell.data/.*
- ./docs/WW/osgi-plugin.data/.*
- ./docs/WW/portlet-tutorial-webwork-22.data/.*
- ./docs/WW/processing-forms.data/.*
- ./docs/WW/struts-2-form-tags.data/.*
- ./docs/WW/struts-2-portlet-tutorial.data/.*
- ./docs/WW/the-struts-2-request-flow.data/.*
- ./docs/WW/using-struts-2-tags.data/.*
- ./docs/WW/using-tags.data/.*
- ./docs/WW/wildcard-method-selection.data/.*
- ./lib/.*
- ./lib/plugins/.*
- ./lib/plugins/embeddedjsp/.*
- ./lib/xwork-core/.*
